server:
  port: 20001

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:15432}/${POSTGRES_DB:ticketing}?currentSchema=${USER_SCHEMA:user_service}
    username: ${POSTGRES_USER:ticketing}
    password: ${POSTGRES_PASSWORD:${DB_PASSWORD:change-me-local}}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${USER_SCHEMA:user_service}
        hbm2ddl:
          create_schemas: true
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/ticketing

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10001/eureka/
      
