server:
  port: 20001

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:15432/ticketing
    username: ticketing
    password: ${DB_PASSWORD:change-me-local}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/ticketing

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10001/eureka/
      
